spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          public-key-location: 'classpath:/pub.pem'


management:
  endpoints:
    web:
      exposure:
        include:
          - info
          - health

# custom.resource.audience: https://gate.acn.dev/acn-api