security.oauth2.resource:
  jwk.key-set-uri: https://acnbank.auth0.com/.auth0.com/.well-known/jwks.json


management:
  endpoints:
    web:
      exposure:
        include:
          - info
          - health
          - metrics
          - loggers
  endpoint:
    beans:
      enabled: false

custom.resource.audience: https://gate.acn.dev/acn-api